# Generated by Django 3.2.3 on 2022-05-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sum', models.FloatField()),
                ('date', models.DateTimeField()),
                ('type', models.IntegerField(choices=[(-1, 'Wydatek'), (1, 'Przychód')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgethandling.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgethandling.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Recurring_Expense',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budgethandling.transaction')),
                ('interval_days', models.IntegerField()),
                ('interval_weeks', models.IntegerField()),
                ('interval_months', models.IntegerField()),
                ('interval_years', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            bases=('budgethandling.transaction',),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgethandling.myuser'),
        ),
    ]
