# Generated by Django 3.2.3 on 2022-05-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgethandling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.FloatField(choices=[(-1, 'Wydatek'), (1, 'Przychód')]),
        ),
    ]
