# Generated by Django 4.0.4 on 2022-06-04 21:11

from django.db import migrations, models
import django.db.models.deletion
import django_matplotlib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('budgethandling', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wydatki_kategorie', django_matplotlib.fields.MatplotlibFigureField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgethandling.myuser')),
            ],
        ),
    ]
