# Generated by Django 4.0.4 on 2022-06-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgethandling', '0003_plots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date',)},
        ),
    ]
